Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The default value for `options.encrypt` will change from `false` to `true`. Please pass `false` explicitly if you want to retain current behaviour. at node_modules\mssql\lib\tedious.js:212:23
Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The `IntN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:63:20
Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The `BitN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:71:40
Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The `FloatN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:73:20
Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The `MoneyN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:78:20
Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The `NumericN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:82:44
Mon, 13 Aug 2018 06:12:46 GMT tedious deprecated The `DecimalN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:83:44
Mon, 13 Aug 2018 06:12:49 GMT tedious deprecated The `DateTimeN` data type is internal and will be removed. at node_modules\mssql\lib\tedious.js:85:20
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\menuController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\dashboardController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\dashboardtaskController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\loginController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Already connecting to database! Call close before connecting to different database.
    at ConnectionPool._connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:233:23)
    at PromiseLibrary (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:215:19)
    at new Promise (<anonymous>)
    at ConnectionPool.connect (D:\SynchronryDashboardAPI\node_modules\mssql\lib\base.js:214:12)
    at D:\SynchronryDashboardAPI\controller\dashboardtaskController.js:12:14
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\SynchronryDashboardAPI\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\SynchronryDashboardAPI\node_modules\express\lib\router\layer.js:95:5)
    at D:\SynchronryDashboardAPI\node_modules\express\lib\router\index.js:281:22 code: 'EALREADYCONNECTING', name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
{ ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at Connection.tedious.once.err (D:\SynchronryDashboardAPI\node_modules\mssql\lib\tedious.js:216:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:12)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to ATLT954\SQLEXPRESS in 15000ms
    at ConnectionError (D:\SynchronryDashboardAPI\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:936:28)
    at Timeout._onTimeout (D:\SynchronryDashboardAPI\node_modules\tedious\lib\connection.js:906:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
     message: 'Failed to connect to ATLT954\\SQLEXPRESS in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
